### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by ytmsuhsff** [bbc/waveform-data.js#105] opened 2022-03-26 03:55 UTC
Hello, I installed wavesurfer JS audio wave display, but the wave loading speed is very slow. You need to save the wave to the database to load the wave quickly. Is it possible to solve this problem.
(wavesurfer.js https://wavesurfer-js.org/ )

Just like them
https://icons8.com/music/search/beach
https://tunetank.com/tracks/

This is my website
http://www.partymusic.cn/

我的邮件 [304955091@qq.com](mailto:304955091@qq.com)

**Comment by chrisn** [comment] 2022-03-29 20:05
Closing as duplicate of https://github.com/bbc/audiowaveform/issues/164

**Closed by chrisn** 2022-03-29 20:05 UTC
